#ifndef CMCI_VERSION_H
#define CMCI_VERSION_H

#define CMCI_VERSION_MAJOR 0
#define CMCI_VERSION_MINOR 1
#define CMCI_VERSION_PATCH 0

#define CMCI_VERSION_STRING "0.1.0"

#endif /* CMCI_VERSION_H */
